###
GET https://127.0.0.1:8080/user

###
GET https://127.0.0.1:8080/user/ed73d59f-a950-4131-939d-305fad83bf021

###
POST https://127.0.0.1:8080/user
Content-Type: application/json

{
  "username": "nihil1",
  "email": "ema1",
  "password": "password"
}

